image: gradle:jdk11

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

before_script:
  - cd ./BookCaseMultiProject
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - gradle --build-cache assemble
    - gradle jar
  artifacts:
    paths:
      - ./BookCaseMultiProject/app/build/libs/app.jar
    expire_in: 1 week
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - ./BookCaseMultiProject/build
      - ./BookCaseMultiProject/.gradle

test:
  stage: test
  script:
    - gradle check
    - gradle app:checkstyleMain
    - gradle app:checkstyleTest
    - gradle core:checkstyleMain
    - gradle core:checkstyleTest
    - gradle core:spotbugsMain
    - gradle core:spotbugsTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - ./BookCaseMultiProject/build
      - ./BookCaseMultiProject/.gradle